services:
  - type: web
    name: esf-thamara-backend
    env: node
    plan: free
    repo: https://github.com/IvanM1999/ESF-Thamara
    branch: main
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campanha-uniasselvi
          property: connectionString
      - key: JWT_SECRET
        sync: true   # definido automaticamente no painel do Render

  - type: web
    name: Campanha-Uniasselvi
    env: static
    plan: free
    repo: https://github.com/IvanM1999/CampanhaFaculdade
    branch: main
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/public

databases:
  - name: campanha-db
    plan: starter
    databaseName: campanha
    user: esf_user
